name: Update Yield Curve

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy plotly quandl matplotlib ipywidgets ipykernel

    - name: Generate HTML
      run: python yield_curve_3d_us.py

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
        git add yield_curve_3d.html
        CURRENT_DATE=$(date +%Y-%m-%d)
        git commit -m "Update yield curve 3D HTML for ${CURRENT_DATE}" || echo "No changes to commit"
        git push

