name: Update Yield Curve

on:
  schedule:
    - cron: '*/10 * * * *'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy plotly quandl matplotlib ipywidgets ipykernel

    - name: Generate HTML
      run: python yield_curve_3d_us.py

    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Commit changes
      run: |
        git add yield_curve_3d_us.html
        CURRENT_DATE=$(date +%Y-%m-%d)
        git commit --allow-empty -m "Update yield curve 3D HTML for ${CURRENT_DATE} -- Empty commit" || echo "No changes to commit"

    - name: Push changes
      uses: ad-m/github-push-action@ma
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}




